version: '3'
networks:
  evaluation:

services:
  aido-host:
    environment:
      FLEET_SIZE: '20'
      REQUESTS_SIZE: '500'
      SCENARIO: SanFrancisco.20080519
      challenge_name: aido2_amod_service_quality_r1-v4
      challenge_step_name: step1-simulation

      username: ${USER}
    build:
      context: ./aido-host
    networks:
      evaluation:
        aliases:
        - evaluation
    volumes:
    - ./out-challenges:/challenges:rw

  solution:
    build:
      context: ../challenge-aido1_amod1-template-python
    environment:
      username: ${USER}
      challenge_name: aido2_amod_service_quality_r1-v4
      challenge_step_name: step1-simulation

    networks:
      evaluation:
        aliases:
        - evaluation

    volumes:
      - ./out-challenges:/challenges:rw
volumes:
  fifos: {}
